social_project/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'signup/$', views.SignUp.as_view(), name='signup')
]

social_project/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
    url(r'^feed', views.feed, name='feed')
    ]

social_project/recipes/urls.py
from django.conf.urls import url

from . import views

app_name='recipes'


urlpatterns = [
    url(r"^$", views.recipe_base, name="recipe_base"),
    url(r'^rotd/$', views.rotd, name='rotd')

    ]

social_project/social_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'accounts/', include('accounts.urls', namespace='accounts')),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^recipes/', include('recipes.urls', namespace='recipes'))

]

social_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Saffron</title>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">


    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'social_project/css/master.css' %}">



  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light mynav" style="background-color: #FF7F64;">
      <a class="navbar-brand mynav" href="{% url 'home' %}"> <strong>Saffron</strong></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:all' %}">My Feed</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:create' %}">Post</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'groups:create' %}">Create Group</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'recipes:rotd' %}">ROTD</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
            </li>


          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
            </li>

          {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>



        </ul>

      </div>
    </nav>


    <div class="mycontent">
      {% block content_block %}

      {% endblock %}
    </div>


    </div>


    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

<canvas id="canvas"></canvas>

  </body>
  {# <script src="{% static "social_project/js/master.js"%}" type="text/javascript" ></script> #}
</html>

social_project/templates/index.html
{% extends "base.html" %}

{% block content_block %}

<div class="site-title">
  <h1> <strong>Welcome to Saffron!</strong> </h1>
  <h2>The Social Network for Foodies.</h2>
  <p class="content col-md-5">Saffron is a social hub for those who love to cook, eat, and share. Join a group, or create your own and share your favorite recipes, document photos of your best work, or just chat with members! Have fun! </p>
</div>





{% endblock %}

social_project/templates/test.html
{% extends "base.html" %}

{% block content_block %}
<div class="site-title">
<h1>You are now logged in!</h1>
</div>


{% endblock %}

social_project/templates/thanks.html
{% extends "base.html" %}

{% block content_block %}

<div class="site-title">
<h1>You have successfully logged out.</h1>
</div>

{% endblock  %}